loadbalancer:
  ports:
  - 8080:80
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - app1:app1
  stdin_open: true
app1:
  ports:
  - 80:80/tcp
  restart: always
  environment:
    BUILDOUT_ZEO_CLIENT: 'True'
    BUILDOUT_ZEO_ADDRESS: zeo:8100
  tty: true
  image: eeacms/plone
  links:
  - zeo:zeo
  stdin_open: true
zeo:
  ports:
  - 8100:8100/tcp
  restart: always
  tty: true
  image: eeacms/zeoserver
  stdin_open: true
